import type { NextPage } from "next";
import Head from "next/head";
import HeaderComponent from "../components/Header/HeaderComponent";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next PokeApi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <HeaderComponent />
      </header>
    </div>
  );
};

export default Home;
