import type { NextPage } from "next";
import Head from "next/head";
import BodyComponent from "../components/Body/BodyComponent";
import FooterComponent from "../components/Footer/FooterComponent";
import HeaderComponent from "../components/Header/HeaderComponent";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PokeAPI - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderComponent />
        <BodyComponent />
        <FooterComponent />
      </main>
    </div>
  );
};

export default Home;
