import type { NextPage } from "next";
import Head from "next/head";
import FooterComponent from "../components/Footer/FooterComponent";
import HeaderComponent from "../components/Header/HeaderComponent";

import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PokeAPI - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderComponent />
        <Image
          src="/images/Pokemon.png"
          alt="Pokemon-Logo"
          width="100%"
          height="36%"
          layout="responsive"
        />
        <FooterComponent />
      </main>
    </div>
  );
};

export default Home;
