import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import FooterComponent from "../components/Footer/FooterComponent";
import HeaderComponent from "../components/Header/HeaderComponent";

import style from "../styles/Home.module.css";

interface Props {
  results: [];
}

interface Pokemon {
  name: string;
  url: string;
}

const Pokemon = (props: Props) => {
  const { results } = props;
  let id = 0;

  return (
    <div>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderComponent />
        <div className={style.container}>
          {results.map((pokemon: Pokemon) => {
            id++;
            return (
              <Link key={pokemon.name} href={`/pokemon/${pokemon.name}`}>
                <div className={style.border}>
                  <div className={style.superior}>
                    <Image
                      src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/${id}.gif`}
                      alt={pokemon.name}
                      width={110}
                      height={90}
                    />
                  </div>
                  <div className={style.superior_circle}>
                    <div className={style.interior_circle}></div>
                  </div>
                  <div className={style.inferior}>
                    <span className={style.pokemonName}>{pokemon.name}</span>
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
        <FooterComponent />
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  const req = await fetch("https://pokeapi.co/api/v2/pokemon/");
  const res = await req.json();

  return {
    props: res,
  };
}

export default Pokemon;
