import Head from "next/head";
import React from "react";
import HeaderComponent from "../components/Header/HeaderComponent";

const Pokemon = () => {
  return (
    <div>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderComponent />
      </main>
    </div>
  );
};

export default Pokemon;
