import Head from "next/head";
import React, { useState } from "react";
import BodyComponent from "../components/Body/BodyComponent";
import FooterComponent from "../components/Footer/FooterComponent";
import HeaderComponent from "../components/Header/HeaderComponent";

interface Props {
  results: [];
}

const Pokemon = (props: Props) => {
  const { results } = props;

  return (
    <div>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeaderComponent />
        <BodyComponent pokemon={results} />
        <FooterComponent />
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  const req = await fetch("https://pokeapi.co/api/v2/pokemon/");
  const res = await req.json();

  return {
    props: res,
  };
}

export default Pokemon;
