import { GetStaticProps, GetStaticPaths, GetServerSideProps } from "next";
import Head from "next/head";
import Pokemon from "../pokedex";

interface Pokemon {
  name: string;
}

export const getStaticPaths: GetStaticPaths = async () => {
  const req = await fetch("https://pokeapi.co/api/v2/pokemon");
  const res = await req.json();

  const paths = res.results.map((pokemon: Pokemon) => {
    return {
      params: { name: pokemon.name },
    };
  });

  return {
    paths: paths,
    fallback: false, // can also be true or 'blocking'
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const pokemonName = context.params?.name;

  const req = await fetch(`https://pokeapi.co/api/v2/pokemon/${pokemonName}`);
  const res = await req.json();

  return {
    props: res,
  };
};

export default function PokemonName(props: Pokemon) {
  console.log(props);

  return (
    <div>
      <Head>
        <title>Pokemon - {props.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>{props.name}</h2>
    </div>
  );
}
